// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: blogs.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createBlog = `-- name: CreateBlog :one
insert into blogs(
    id, title, brief, content_url,
    images, thumbnail_url, code_repo_link, tags,
    author, category, created_at, updated_at
) values(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    NOW(),
    NOW()
)
returning id, title, brief, content_url, images, thumbnail_url, code_repo_link, views, likes, tags, author, category, created_at, updated_at
`

type CreateBlogParams struct {
	Title        string
	Brief        string
	ContentUrl   string
	Images       json.RawMessage
	ThumbnailUrl string
	CodeRepoLink sql.NullString
	Tags         string
	Author       uuid.UUID
	Category     uuid.UUID
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog,
		arg.Title,
		arg.Brief,
		arg.ContentUrl,
		arg.Images,
		arg.ThumbnailUrl,
		arg.CodeRepoLink,
		arg.Tags,
		arg.Author,
		arg.Category,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Brief,
		&i.ContentUrl,
		&i.Images,
		&i.ThumbnailUrl,
		&i.CodeRepoLink,
		&i.Views,
		&i.Likes,
		&i.Tags,
		&i.Author,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dislikeBlog = `-- name: DislikeBlog :exec
delete from likes where user_id = $1 and blog_id = $2
`

type DislikeBlogParams struct {
	UserID uuid.UUID
	BlogID uuid.UUID
}

func (q *Queries) DislikeBlog(ctx context.Context, arg DislikeBlogParams) error {
	_, err := q.db.ExecContext(ctx, dislikeBlog, arg.UserID, arg.BlogID)
	return err
}

const getAllBlogsByCategory = `-- name: GetAllBlogsByCategory :many
select 
id, title, brief, thumbnail_url, views, likes,
tags, created_at from blogs where category = $1 and id > $2 limit $3
`

type GetAllBlogsByCategoryParams struct {
	Category uuid.UUID
	ID       uuid.UUID
	Limit    int32
}

type GetAllBlogsByCategoryRow struct {
	ID           uuid.UUID
	Title        string
	Brief        string
	ThumbnailUrl string
	Views        int32
	Likes        int32
	Tags         string
	CreatedAt    time.Time
}

func (q *Queries) GetAllBlogsByCategory(ctx context.Context, arg GetAllBlogsByCategoryParams) ([]GetAllBlogsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlogsByCategory, arg.Category, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBlogsByCategoryRow
	for rows.Next() {
		var i GetAllBlogsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Brief,
			&i.ThumbnailUrl,
			&i.Views,
			&i.Likes,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogByID = `-- name: GetBlogByID :one
select
blogs.title, blogs.brief, blogs.content_url, blogs.images, blogs.thumbnail_url,
blogs.code_repo_link, blogs.views, blogs.likes,
blogs.tags, users.username, blogs.created_at
from blogs join users on blogs.author = users.id where blogs.id = $1
`

type GetBlogByIDRow struct {
	Title        string
	Brief        string
	ContentUrl   string
	Images       json.RawMessage
	ThumbnailUrl string
	CodeRepoLink sql.NullString
	Views        int32
	Likes        int32
	Tags         string
	Username     string
	CreatedAt    time.Time
}

func (q *Queries) GetBlogByID(ctx context.Context, id uuid.UUID) (GetBlogByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBlogByID, id)
	var i GetBlogByIDRow
	err := row.Scan(
		&i.Title,
		&i.Brief,
		&i.ContentUrl,
		&i.Images,
		&i.ThumbnailUrl,
		&i.CodeRepoLink,
		&i.Views,
		&i.Likes,
		&i.Tags,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const getNumberOfLikes = `-- name: GetNumberOfLikes :one
select count(*) as noOfLikes from likes where blog_id = $1
`

func (q *Queries) GetNumberOfLikes(ctx context.Context, blogID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfLikes, blogID)
	var nooflikes int64
	err := row.Scan(&nooflikes)
	return nooflikes, err
}

const getViewCount = `-- name: GetViewCount :one
select views from blogs where id = $1
`

func (q *Queries) GetViewCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getViewCount, id)
	var views int32
	err := row.Scan(&views)
	return views, err
}

const hasUserLikedBlog = `-- name: HasUserLikedBlog :one
select 1 from likes where user_id = $1 and blog_id = $2
`

type HasUserLikedBlogParams struct {
	UserID uuid.UUID
	BlogID uuid.UUID
}

func (q *Queries) HasUserLikedBlog(ctx context.Context, arg HasUserLikedBlogParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, hasUserLikedBlog, arg.UserID, arg.BlogID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementViews = `-- name: IncrementViews :exec
update blogs set views = views + 1 where id = $1
`

func (q *Queries) IncrementViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementViews, id)
	return err
}

const likeBlog = `-- name: LikeBlog :exec
insert into likes(user_id, blog_id, created_at, updated_at)
values($1, $2, NOW(), NOW())
`

type LikeBlogParams struct {
	UserID uuid.UUID
	BlogID uuid.UUID
}

func (q *Queries) LikeBlog(ctx context.Context, arg LikeBlogParams) error {
	_, err := q.db.ExecContext(ctx, likeBlog, arg.UserID, arg.BlogID)
	return err
}

const removeBlog = `-- name: RemoveBlog :exec
delete from blogs where id = $1
`

func (q *Queries) RemoveBlog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeBlog, id)
	return err
}

const updateBlog = `-- name: UpdateBlog :one
update blogs set
title = $1, brief = $2, content_url = $3, images = $4,
thumbnail_url = $5, code_repo_link = $6, tags = $7,
category = $8, updated_at = NOW() where id = $9
returning created_at, updated_at
`

type UpdateBlogParams struct {
	Title        string
	Brief        string
	ContentUrl   string
	Images       json.RawMessage
	ThumbnailUrl string
	CodeRepoLink sql.NullString
	Tags         string
	Category     uuid.UUID
	ID           uuid.UUID
}

type UpdateBlogRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (UpdateBlogRow, error) {
	row := q.db.QueryRowContext(ctx, updateBlog,
		arg.Title,
		arg.Brief,
		arg.ContentUrl,
		arg.Images,
		arg.ThumbnailUrl,
		arg.CodeRepoLink,
		arg.Tags,
		arg.Category,
		arg.ID,
	)
	var i UpdateBlogRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}
