// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID           uuid.UUID
	Title        string
	Brief        string
	ContentUrl   string
	Images       []json.RawMessage
	ThumbnailUrl string
	CodeRepoLink string
	Views        int32
	Likes        int32
	Tags         string
	Author       uuid.UUID
	Category     uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Book struct {
	ID            uuid.UUID
	Name          string
	CoverImageUrl string
	Review        string
	Tags          string
	Level         uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BookLevel struct {
	ID        uuid.UUID
	Level     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Category struct {
	ID        uuid.UUID
	Category  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Comment struct {
	ID          uuid.UUID
	Description string
	Likes       int32
	UserID      uuid.UUID
	BlogID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdateAt  time.Time
}

type Role struct {
	ID        uuid.UUID
	RoleName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	Username      string
	ProfilePicUrl string
	Password      string
	RoleID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
