// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :exec
insert into users(id, email, username, profile_pic_url, password, role_id, created_at, updated_at)
values(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
`

type CreateUserParams struct {
	Email         string
	Username      string
	ProfilePicUrl string
	Password      string
	RoleID        uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.ProfilePicUrl,
		arg.Password,
		arg.RoleID,
	)
	return err
}

const getUserByEmailID = `-- name: GetUserByEmailID :one
select users.id, users.username, users.profile_pic_url, users.password, roles.role_name from users join roles on users.role_id = roles.id where users.email = $1
`

type GetUserByEmailIDRow struct {
	ID            uuid.UUID
	Username      string
	ProfilePicUrl string
	Password      string
	RoleName      string
}

func (q *Queries) GetUserByEmailID(ctx context.Context, email string) (GetUserByEmailIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailID, email)
	var i GetUserByEmailIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ProfilePicUrl,
		&i.Password,
		&i.RoleName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select 
    email, 
    username, 
    profile_pic_url, 
    created_at, 
    updated_at
    from users where id = $1
`

type GetUserByIDRow struct {
	Email         string
	Username      string
	ProfilePicUrl string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
select role_id from users where users.id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, id)
	var role_id uuid.UUID
	err := row.Scan(&role_id)
	return role_id, err
}

const removeUser = `-- name: RemoveUser :exec
delete from users where id = $1
`

func (q *Queries) RemoveUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeUser, id)
	return err
}

const searchBlogsByTags = `-- name: SearchBlogsByTags :many
select id, title, brief, thumbnail_url, views from blogs
where tags && $1
`

type SearchBlogsByTagsRow struct {
	ID           uuid.UUID
	Title        string
	Brief        string
	ThumbnailUrl string
	Views        int32
}

func (q *Queries) SearchBlogsByTags(ctx context.Context, tags []string) ([]SearchBlogsByTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBlogsByTags, pq.Array(tags))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBlogsByTagsRow
	for rows.Next() {
		var i SearchBlogsByTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Brief,
			&i.ThumbnailUrl,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBlogsByTitle = `-- name: SearchBlogsByTitle :many
select id, title, brief, thumbnail_url, views from blogs
where title ilike $1 or title ilike $2 or title ilike $3
`

type SearchBlogsByTitleParams struct {
	Title   string
	Title_2 string
	Title_3 string
}

type SearchBlogsByTitleRow struct {
	ID           uuid.UUID
	Title        string
	Brief        string
	ThumbnailUrl string
	Views        int32
}

func (q *Queries) SearchBlogsByTitle(ctx context.Context, arg SearchBlogsByTitleParams) ([]SearchBlogsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBlogsByTitle, arg.Title, arg.Title_2, arg.Title_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBlogsByTitleRow
	for rows.Next() {
		var i SearchBlogsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Brief,
			&i.ThumbnailUrl,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksByTags = `-- name: SearchBooksByTags :many
select id, name, cover_image_url from books
where tags && $1
`

type SearchBooksByTagsRow struct {
	ID            uuid.UUID
	Name          string
	CoverImageUrl string
}

func (q *Queries) SearchBooksByTags(ctx context.Context, tags []string) ([]SearchBooksByTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksByTags, pq.Array(tags))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksByTagsRow
	for rows.Next() {
		var i SearchBooksByTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CoverImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksByTitle = `-- name: SearchBooksByTitle :many
select id, name, cover_image_url from books
where name ilike $1 and name ilike $2 and name ilike $3
`

type SearchBooksByTitleParams struct {
	Name   string
	Name_2 string
	Name_3 string
}

type SearchBooksByTitleRow struct {
	ID            uuid.UUID
	Name          string
	CoverImageUrl string
}

func (q *Queries) SearchBooksByTitle(ctx context.Context, arg SearchBooksByTitleParams) ([]SearchBooksByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksByTitle, arg.Name, arg.Name_2, arg.Name_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksByTitleRow
	for rows.Next() {
		var i SearchBooksByTitleRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CoverImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmail = `-- name: UpdateEmail :exec
update users set email = $1, updated_at = NOW() where id = $2
`

type UpdateEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updateOtherDetails = `-- name: UpdateOtherDetails :one
update users set username = $1, profile_pic_url = $2, updated_at = NOW() where id = $3
returning username, profile_pic_url
`

type UpdateOtherDetailsParams struct {
	Username      string
	ProfilePicUrl string
	ID            uuid.UUID
}

type UpdateOtherDetailsRow struct {
	Username      string
	ProfilePicUrl string
}

func (q *Queries) UpdateOtherDetails(ctx context.Context, arg UpdateOtherDetailsParams) (UpdateOtherDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, updateOtherDetails, arg.Username, arg.ProfilePicUrl, arg.ID)
	var i UpdateOtherDetailsRow
	err := row.Scan(&i.Username, &i.ProfilePicUrl)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
update users set password = $1, updated_at = NOW() where id = $2
`

type UpdatePasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const userExist = `-- name: UserExist :one
select exists(select 1 from users where email = $1)
`

func (q *Queries) UserExist(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExist, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
